import { writeFile, mkdir } from 'fs/promises';
import { dirname } from 'path';
import { load } from './storage.js';

const TARGET = process.env.PUBLISH_DATA_JS || '';

// Legacy publisher: regenerates a JS bundle for the old static site.
// The new React/Vite site fetches /admin/api/public/content directly,
// so this is a no-op unless PUBLISH_DATA_JS is set explicitly.
export async function publish() {
  if (!TARGET) return { ok: true, skipped: true, reason: 'PUBLISH_DATA_JS not set' };
  const c = await load();
  const out = render(c);
  await mkdir(dirname(TARGET), { recursive: true });
  await writeFile(TARGET, out, 'utf8');
  return { ok: true, target: TARGET, bytes: out.length, ts: Date.now() };
}

function render(c) {
  return [
    '// FinLingvo — auto-generated by admin (do not edit by hand)',
    `// generated: ${new Date().toISOString()}`,
    '',
    `const MODULES = ${JSON.stringify(c.modules || [], null, 2)};`,
    '',
    `const ACHIEVEMENTS = ${JSON.stringify(c.achievements || [], null, 2)};`,
    '',
    `const LEAGUES = ${JSON.stringify(c.leagues || [], null, 2)};`,
    '',
    `const SHOP_ITEMS = ${JSON.stringify(c.shop_items || [], null, 2)};`,
    '',
    'window.FL_DATA = { MODULES, ACHIEVEMENTS, LEAGUES, SHOP_ITEMS };',
    '',
  ].join('\n');
}
